#!/bin/sh -e

#DEBHELPER#

if ! getent passwd swift > /dev/null ; then
  adduser --system --quiet --disabled-login --home /var/lib/swift \
        --disabled-password --no-create-home --group \
        --shell /usr/sbin/nologin swift
fi

usermod -G adm swift

find /etc/swift -exec chown root:swift "{}" +
find /etc/swift -type f -exec chmod 0640 "{}" + -o -type d -exec chmod 0750 "{}" +

if [ -d /var/cache/swift ] ; then
  # Allow swift user to write to cache directory
  chown root:swift /var/cache/swift
  chmod 0775 /var/cache/swift
fi

exit 0
